[package]
name = "bandit"
version = "0.12.1"
authors = ["Michael Bohn <michael.bohn@freiheit.com>"]
description = "Bandit Algorithms in Rust"
license = "GPL-3.0"
repository = "https://github.com/Ragnaroek/bandit"

[dependencies]
rand = "0.6.5"
serde = "1.0.90"
serde_json = "1.0.39"
serde_derive = "1.0.90"

[dev-dependencies]
regex = "1.1.6"
